// Biblioteca de ejercicios — HubFit App
// Formato compacto: [nombre, grupo muscular]
window.LIBRARY = [
  // A
  ['Abdominal Thrusts', 'Abs'],
  ['Adductor Machine', 'Adductors'],
  ['Ankle Circles', 'Other'],
  ['Archer Pull-up', 'Back'],
  ['Archer Row Under Table', 'Back'],
  ['Arm Circles', 'Shoulders'],
  ['Arm Flap Hops', 'Other'],
  ['Arnold Press', 'Shoulders'],
  ['Assisted Pull-up', 'Back'],
  ['Assisted Tricep Dip', 'Triceps'],
  // B
  ['Back Extension', 'Lower Back'],
  ['Backward Lunge', 'Quadriceps'],
  ['Balance Beam Walk', 'Other'],
  ['Barbell Bench Press', 'Chest'],
  ['Barbell Bulgarian Split Squat', 'Quadriceps'],
  ['Barbell Clean and Jerk', 'Other'],
  ['Barbell Clean and Press', 'Other'],
  ['Barbell Concentration Curl', 'Biceps'],
  ['Barbell Curl', 'Biceps'],
  ['Barbell Deadlift', 'Back'],
  ['Barbell Front Rack Lunge', 'Quadriceps'],
  ['Barbell Front Squat', 'Quadriceps'],
  ['Barbell Full Squat', 'Quadriceps'],
  ['Barbell Glute Bridge', 'Glutes'],
  ['Barbell Good Morning', 'Lower Back'],
  ['Barbell Hack Squat', 'Quadriceps'],
  ['Barbell Hip Thrust', 'Glutes'],
  ['Barbell Incline Bench Press', 'Chest'],
  ['Barbell Incline Row', 'Back'],
  ['Barbell Lateral Lunge', 'Adductors'],
  ['Barbell Lunge', 'Quadriceps'],
  ['Barbell Military Press', 'Shoulders'],
  ['Barbell Overhead Squat', 'Shoulders'],
  ['Barbell Power Clean', 'Other'],
  ['Barbell Preacher Curl', 'Biceps'],
  ['Barbell Rear Delt Row', 'Shoulders'],
  ['Barbell Reverse Curl', 'Biceps'],
  ['Barbell Reverse Lunge', 'Quadriceps'],
  ['Barbell Romanian Deadlift', 'Hamstrings'],
  ['Barbell Row', 'Back'],
  ['Barbell Shrug', 'Traps'],
  ['Barbell Side Split Squat', 'Adductors'],
  ['Barbell Squat', 'Quadriceps'],
  ['Barbell Standing Calf Raise', 'Calves'],
  ['Barbell Standing Military Press', 'Shoulders'],
  ['Barbell Step Up', 'Quadriceps'],
  ['Barbell Sumo Deadlift', 'Hamstrings'],
  ['Barbell Sumo Squat', 'Quadriceps'],
  ['Barbell Upright Row', 'Traps'],
  ['Barbell Wrist Curl', 'Forearms'],
  ['Battle Rope Alternating Waves', 'Other'],
  ['Battle Rope Double Waves', 'Other'],
  ['Bear Crawl', 'Other'],
  ['Bench Dip', 'Triceps'],
  ['Bent Knee Hip Raise', 'Abs'],
  ['Bent Over Dumbbell Raise', 'Shoulders'],
  ['Bird Dog', 'Core'],
  ['Body Weight Squat', 'Quadriceps'],
  ['Box Jump', 'Other'],
  ['Bridge', 'Glutes'],
  ['Bulgarian Split Squat', 'Quadriceps'],
  ['Burpee', 'Other'],
  ['Butterfly Stretch', 'Other'],
  // C
  ['Cable Concentration Extension', 'Triceps'],
  ['Cable Crossover', 'Chest'],
  ['Cable Crunch', 'Abs'],
  ['Cable Curl', 'Biceps'],
  ['Cable Decline Fly', 'Chest'],
  ['Cable Face Pull', 'Shoulders'],
  ['Cable Fly', 'Chest'],
  ['Cable Half Kneeling Curl', 'Biceps'],
  ['Cable Half Kneeling Pull', 'Back'],
  ['Cable Hammer Curl', 'Biceps'],
  ['Cable High Row', 'Back'],
  ['Cable Hip Abduction', 'Abductors'],
  ['Cable Hip Extension', 'Glutes'],
  ['Cable Incline Fly', 'Chest'],
  ['Cable Incline Pushdown', 'Triceps'],
  ['Cable Kickback', 'Triceps'],
  ['Cable Kneeling Hip Flexion', 'Hip Flexors'],
  ['Cable Kneeling Pull Through', 'Glutes'],
  ['Cable Kneeling Single Leg', 'Hamstrings'],
  ['Cable Lateral Raise', 'Shoulders'],
  ['Cable Lateral Rotation', 'Other'],
  ['Cable Low Row', 'Back'],
  ['Cable Lying Tricep Extension', 'Triceps'],
  ['Cable One Arm Curl', 'Biceps'],
  ['Cable One Arm Lateral Raise', 'Shoulders'],
  ['Cable One Arm Row', 'Back'],
  ['Cable Overhead Tricep Extension', 'Triceps'],
  ['Cable Pull Through', 'Glutes'],
  ['Cable Rear Delt Fly', 'Shoulders'],
  ['Cable Rear Lateral Raise', 'Shoulders'],
  ['Cable Reverse Curl', 'Biceps'],
  ['Cable Reverse Fly', 'Shoulders'],
  ['Cable Row', 'Back'],
  ['Cable Seated Row', 'Back'],
  ['Cable Shrug', 'Traps'],
  ['Cable Side Bend', 'Obliques'],
  ['Cable Single Arm Neutral Grip Row', 'Back'],
  ['Cable Single Leg Hip Extension', 'Glutes'],
  ['Cable Single Leg Romanian Deadlift', 'Hamstrings'],
  ['Cable Squat', 'Quadriceps'],
  ['Cable Standing Hip Abduction', 'Abductors'],
  ['Cable Standing Hip Extension', 'Glutes'],
  ['Cable Standing Hip Flexion', 'Hip Flexors'],
  ['Cable Standing Inner Curl with Supinator Obliquus', 'Biceps'],
  ['Cable Standing Low Fly', 'Chest'],
  ['Cable Standing Neutral Grip Fly', 'Chest'],
  ['Cable Standing Pulldown', 'Back'],
  ['Cable Standing Reverse Fly', 'Shoulders'],
  ['Cable Standing Single Arm Fly', 'Chest'],
  ['Cable Standing Single Arm Row', 'Back'],
  ['Cable Standing Single Leg Curl', 'Hamstrings'],
  ['Cable Standing Single Leg Deadlift', 'Hamstrings'],
  ['Cable Standing Straight Arm Lat Pulldown', 'Back'],
  ['Cable Standing Tricep Pushdown', 'Triceps'],
  ['Cable Standing Upright Row', 'Traps'],
  ['Cable Straight Arm Pulldown', 'Back'],
  ['Cable Tricep Extension', 'Triceps'],
  ['Cable Tricep Kickback', 'Triceps'],
  ['Cable Tricep Overhead Extension', 'Triceps'],
  ['Cable Tricep Pushdown', 'Triceps'],
  ['Cable Two Arm Curl', 'Biceps'],
  ['Cable Upright Row', 'Traps'],
  ['Cable Woodchop', 'Obliques'],
  ['Calf Raise', 'Calves'],
  ['Cat Cow Stretch', 'Other'],
  ['Chair Dip', 'Triceps'],
  ['Child Pose', 'Other'],
  ['Chin Up', 'Back'],
  ['Close Grip Bench Press', 'Triceps'],
  ['Close Grip Lat Pulldown', 'Back'],
  ['Concentration Curl', 'Biceps'],
  ['Crunch', 'Abs'],
  ['Curtsy Lunge', 'Glutes'],
  // D
  ['Dead Bug', 'Core'],
  ['Dead Hang', 'Back'],
  ['Deadlift', 'Back'],
  ['Decline Bench Press', 'Chest'],
  ['Decline Crunch', 'Abs'],
  ['Decline Push-up', 'Chest'],
  ['Dip', 'Triceps'],
  ['Dips', 'Triceps'],
  ['Donkey Calf Raise', 'Calves'],
  ['Donkey Kick', 'Glutes'],
  ['Double Crunch', 'Abs'],
  ['Dumbbell Alternating Front Raise', 'Shoulders'],
  ['Dumbbell Bench Press', 'Chest'],
  ['Dumbbell Bent Over Row', 'Back'],
  ['Dumbbell Bulgarian Split Squat', 'Quadriceps'],
  ['Dumbbell Concentration Curl', 'Biceps'],
  ['Dumbbell Curl', 'Biceps'],
  ['Dumbbell Deadlift', 'Back'],
  ['Dumbbell Decline Bench Press', 'Chest'],
  ['Dumbbell Flyes', 'Chest'],
  ['Dumbbell Front Raise', 'Shoulders'],
  ['Dumbbell Goblet Squat', 'Quadriceps'],
  ['Dumbbell Good Morning', 'Lower Back'],
  ['Dumbbell Hammer Curl', 'Biceps'],
  ['Dumbbell Hip Thrust', 'Glutes'],
  ['Dumbbell Incline Bench Press', 'Chest'],
  ['Dumbbell Incline Curl', 'Biceps'],
  ['Dumbbell Incline Fly', 'Chest'],
  ['Dumbbell Incline Row', 'Back'],
  ['Dumbbell Kickback', 'Triceps'],
  ['Dumbbell Lateral Raise', 'Shoulders'],
  ['Dumbbell Lunge', 'Quadriceps'],
  ['Dumbbell Lying Tricep Extension', 'Triceps'],
  ['Dumbbell One Arm Row', 'Back'],
  ['Dumbbell Overhead Press', 'Shoulders'],
  ['Dumbbell Overhead Tricep Extension', 'Triceps'],
  ['Dumbbell Preacher Curl', 'Biceps'],
  ['Dumbbell Pullover', 'Back'],
  ['Dumbbell Rear Delt Row', 'Shoulders'],
  ['Dumbbell Reverse Curl', 'Biceps'],
  ['Dumbbell Reverse Fly', 'Shoulders'],
  ['Dumbbell Reverse Lunge', 'Quadriceps'],
  ['Dumbbell Romanian Deadlift', 'Hamstrings'],
  ['Dumbbell Row', 'Back'],
  ['Dumbbell Shrug', 'Traps'],
  ['Dumbbell Side Bend', 'Obliques'],
  ['Dumbbell Single Arm Overhead Press', 'Shoulders'],
  ['Dumbbell Single Leg Romanian Deadlift', 'Hamstrings'],
  ['Dumbbell Squat', 'Quadriceps'],
  ['Dumbbell Step Up', 'Quadriceps'],
  ['Dumbbell Sumo Squat', 'Quadriceps'],
  ['Dumbbell Tricep Kickback', 'Triceps'],
  ['Dumbbell Upright Row', 'Traps'],
  ['Dumbbell Wrist Curl', 'Forearms'],
  // E
  ['EZ Bar Curl', 'Biceps'],
  ['EZ Bar Preacher Curl', 'Biceps'],
  ['EZ Bar Reverse Curl', 'Biceps'],
  ['EZ Bar Skullcrusher', 'Triceps'],
  ['Elevated Push-up', 'Chest'],
  // F
  ['Face Pull', 'Shoulders'],
  ['Farmer Walk', 'Other'],
  ['Fire Hydrant', 'Glutes'],
  ['Flat Bench Press', 'Chest'],
  ['Flutter Kick', 'Abs'],
  ['Forward Lunge', 'Quadriceps'],
  ['Frog Jump', 'Other'],
  ['Front Raise', 'Shoulders'],
  ['Front Squat', 'Quadriceps'],
  // G
  ['Glute Bridge', 'Glutes'],
  ['Glute Kickback', 'Glutes'],
  ['Good Morning', 'Lower Back'],
  ['Goblet Squat', 'Quadriceps'],
  // H
  ['Hack Squat', 'Quadriceps'],
  ['Hammer Curl', 'Biceps'],
  ['Handstand Push-up', 'Shoulders'],
  ['Hanging Knee Raise', 'Abs'],
  ['Hanging Leg Raise', 'Abs'],
  ['High Knees', 'Other'],
  ['Hip Abduction Machine', 'Abductors'],
  ['Hip Adduction Machine', 'Adductors'],
  ['Hip Thrust', 'Glutes'],
  ['Hyperextension', 'Lower Back'],
  // I
  ['Incline Bench Press', 'Chest'],
  ['Incline Curl', 'Biceps'],
  ['Incline Dumbbell Press', 'Chest'],
  ['Incline Push-up', 'Chest'],
  // J
  ['Jackknife Sit-up', 'Abs'],
  ['Jumping Jack', 'Other'],
  ['Jumping Lunge', 'Quadriceps'],
  // K
  ['Kettlebell Goblet Squat', 'Quadriceps'],
  ['Kettlebell Romanian Deadlift', 'Hamstrings'],
  ['Kettlebell Swing', 'Other'],
  ['Kneeling Hip Flexor Stretch', 'Hip Flexors'],
  // L
  ['Lateral Raise', 'Shoulders'],
  ['Lat Pulldown', 'Back'],
  ['Leg Curl', 'Hamstrings'],
  ['Leg Extension', 'Quadriceps'],
  ['Leg Press', 'Quadriceps'],
  ['Leg Press Machine', 'Quadriceps'],
  ['Lunge', 'Quadriceps'],
  ['Lying Leg Curl Machine', 'Hamstrings'],
  ['Lying Tricep Extension', 'Triceps'],
  // M
  ['Machine Chest Fly', 'Chest'],
  ['Machine Chest Press', 'Chest'],
  ['Machine Hip Abduction', 'Abductors'],
  ['Machine Hip Adduction', 'Adductors'],
  ['Machine Row', 'Back'],
  ['Machine Shoulder Press', 'Shoulders'],
  // O
  ['One Arm Dumbbell Row', 'Back'],
  ['One Arm Lat Pulldown', 'Back'],
  ['One Arm Pushdown', 'Triceps'],
  ['Overhead Press', 'Shoulders'],
  ['Overhead Tricep Extension', 'Triceps'],
  // P
  ['Pec Deck', 'Chest'],
  ['Pendulum Squat', 'Quadriceps'],
  ['Pike Push-up', 'Shoulders'],
  ['Plank', 'Core'],
  ['Plank Hip Dip', 'Obliques'],
  ['Preacher Curl', 'Biceps'],
  ['Pull-up', 'Back'],
  ['Pullover', 'Back'],
  ['Push-up', 'Chest'],
  // R
  ['Rear Delt Fly', 'Shoulders'],
  ['Resistance Band Pull Apart', 'Shoulders'],
  ['Reverse Crunch', 'Abs'],
  ['Reverse Fly', 'Shoulders'],
  ['Reverse Grip Lat Pulldown', 'Back'],
  ['Romanian Deadlift', 'Hamstrings'],
  ['Russian Twist', 'Obliques'],
  // S
  ['Seated Cable Row', 'Back'],
  ['Seated Calf Raise', 'Calves'],
  ['Seated Dumbbell Curl', 'Biceps'],
  ['Seated Leg Curl', 'Hamstrings'],
  ['Seated Leg Press', 'Quadriceps'],
  ['Seated Row', 'Back'],
  ['Shoulder Press', 'Shoulders'],
  ['Side Lateral Raise', 'Shoulders'],
  ['Single Arm Cable Row', 'Back'],
  ['Single Leg Deadlift', 'Hamstrings'],
  ['Sit-up', 'Abs'],
  ['Skull Crusher', 'Triceps'],
  ['Smith Machine Squat', 'Quadriceps'],
  ['Squat', 'Quadriceps'],
  ['Standing Calf Raise', 'Calves'],
  ['Step Up', 'Quadriceps'],
  ['Stiff Leg Deadlift', 'Hamstrings'],
  ['Straight Arm Pulldown', 'Back'],
  ['Sumo Deadlift', 'Hamstrings'],
  ['Sumo Squat', 'Quadriceps'],
  ['Superman', 'Lower Back'],
  ['Suspender Bicep Curl', 'Biceps'],
  ['Suspender Crunch', 'Abs'],
  ['Suspender Dip', 'Triceps'],
  ['Suspender Fly', 'Chest'],
  ['Suspender Hamstring Curl', 'Hamstrings'],
  ['Suspender Inverted Row', 'Back'],
  ['Suspender Leg Curl', 'Hamstrings'],
  ['Suspender Lunge', 'Quadriceps'],
  ['Suspender Mountain Climber', 'Other'],
  ['Suspender Pike', 'Abs'],
  ['Suspender Pike Rollout', 'Abs'],
  ['Suspender Plank', 'Core'],
  ['Suspender Pull-up', 'Back'],
  ['Suspender Push-up', 'Chest'],
  ['Suspender Reverse Crunch', 'Abs'],
  ['Suspender Row', 'Back'],
  ['Suspender Side Lunge', 'Adductors'],
  ['Suspender Single Leg Squat', 'Quadriceps'],
  ['Suspender Squat', 'Quadriceps'],
  ['Suspender T', 'Shoulders'],
  // T
  ['T-Bar Row', 'Back'],
  ['Tricep Dip', 'Triceps'],
  ['Tricep Pushdown', 'Triceps'],
  // U
  ['Upright Row', 'Traps'],
  // V
  ['V-Up', 'Abs'],
  // W
  ['Wall Sit', 'Quadriceps'],
  ['Wide Grip Lat Pulldown', 'Back'],
  ['Wide Grip Pull-up', 'Back'],
  // Z
  ['Zottman Curl', 'Biceps']
];
